const status = document.getElementById("status");
const setStatus = (text) => { status.textContent = text; };

async function getSettings() {
  return chrome.storage.local.get(["githubToken", "repo", "branch"]);
}

function detectCategory(title, url) {
  const text = `${title} ${url}`.toLowerCase();
  const rules = [
    ["Arrays", ["array", "subarray", "subsequence", "two sum", "kadane", "rotate array"]],
    ["Strings", ["string", "palindrome", "anagram", "substring"]],
    ["LinkedList", ["linked list", "doubly linked", "circular linked"]],
    ["Stack", ["stack", "parenthesis", "balanced brackets"]],
    ["Queue", ["queue", "deque"]],
    ["Trees", ["binary tree", "bst", "binary search tree", "tree traversal"]],
    ["Graphs", ["graph", "bfs", "dfs", "dijkstra", "topological"]],
    ["Dynamic Programming", ["dynamic programming", "knapsack", "memoization"]],
    ["Searching", ["binary search", "search in", "searching"]],
    ["Sorting", ["sort", "sorting", "merge sort", "quick sort"]],
    ["Mathematics", ["prime", "factorial", "gcd", "lcm", "fibonacci", "number", "divisor", "power"]],
    ["Bit Manipulation", ["bit manipulation", "bitwise", "xor", "set bit"]],
    ["Greedy", ["greedy"]],
    ["Heap", ["heap", "priority queue", "kth largest", "kth smallest"]]
  ];
  for (const [category, words] of rules) if (words.some(w => text.includes(w))) return category;
  return "Miscellaneous";
}

function detectLanguage(code) {
  if (/\bclass\s+Solution\b|System\.out\.println|import\s+java\.|\bpublic\s+static\s+/.test(code)) return "Java";
  if (/\bdef\s+\w+\s*\(|import\s+(numpy|pandas)|\bprint\s*\(/.test(code)) return "Python";
  if (/#include\s*</.test(code) || /std::cout|using\s+namespace\s+std/.test(code)) return "C++";
  if (/console\.log\s*\(|function\s+\w+\s*\(/.test(code)) return "JavaScript";
  return "Java";
}

function extensionFor(language) {
  return { Java: "java", Python: "py", "C++": "cpp", JavaScript: "js" }[language] || "txt";
}

function readme(title, url, language, category) {
  return `# ${title}\n\n- **Platform:** GeeksForGeeks\n- **Category:** ${category}\n- **Language:** ${language}\n- **Problem:** ${url}\n\n## Approach\n\nSolution synced automatically from the GFG editor.\n\n## Notes\n\nThis file was generated by GFG → GitHub Sync.\n`;
}

function b64(text) {
  return btoa(unescape(encodeURIComponent(text)));
}

async function putFile(repo, path, content, message, branch, token) {
  const encodedPath = path.split("/").map(encodeURIComponent).join("/");
  const base = `https://api.github.com/repos/${repo}/contents/${encodedPath}`;
  let sha;
  const existing = await fetch(`${base}?ref=${encodeURIComponent(branch)}`, {
    headers: { Authorization: `Bearer ${token}`, Accept: "application/vnd.github+json" }
  });
  if (existing.ok) sha = (await existing.json()).sha;

  const body = { message, content: b64(content), branch };
  if (sha) body.sha = sha;

  const response = await fetch(base, {
    method: "PUT",
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "Content-Type": "application/json"
    },
    body: JSON.stringify(body)
  });
  const data = await response.json();
  if (!response.ok) throw new Error(data.message || `GitHub HTTP ${response.status}`);
  return data;
}

async function readGfgPage(tabId) {
  const results = await chrome.scripting.executeScript({
    target: { tabId },
    func: () => {
      const clean = (v) => (v || "").replace(/\u00a0/g, " ").replace(/\r/g, "");

      // GFG's current editor is Ace. Reading each .ace_line separately
      // preserves the original line breaks instead of flattening the code.
      const editors = [...document.querySelectorAll(".ace_editor")];
      let best = "";

      for (const editor of editors) {
        const lines = [...editor.querySelectorAll(".ace_text-layer .ace_line")];
        if (lines.length) {
          const code = lines.map(line => clean(line.textContent)).join("\n").trim();
          if (code.length > best.length) best = code;
        }

        // Ace sometimes exposes the actual source through its internal API.
        try {
          if (window.ace) {
            const aceEditor = window.ace.edit(editor);
            const value = aceEditor?.getValue?.();
            if (value && value.length > best.length) best = value;
          }
        } catch (_) {}
      }

      // Fallbacks for editor markup changes.
      if (best.length < 10) {
        for (const el of document.querySelectorAll("textarea, [contenteditable='true'], pre code")) {
          const value = clean(el.value || el.innerText || el.textContent).trim();
          if (value.length > best.length) best = value;
        }
      }

      // Do NOT use the first h1: on some GFG layouts the editor/template
      // contributes its own heading. The document title is safer.
      let title = document.title
        .replace(/\s*\|.*$/, "")
        .replace(/\s*-\s*GeeksforGeeks.*$/i, "")
        .trim();

      const titleCandidates = [
        "h1[class*='problem']",
        "h1[class*='Problem']",
        "[class*='problem-title']",
        "[class*='ProblemTitle']"
      ];
      for (const selector of titleCandidates) {
        const el = document.querySelector(selector);
        const candidate = el?.innerText?.trim();
        if (candidate && candidate.length < 150 && !candidate.includes("class Solution")) {
          title = candidate;
          break;
        }
      }

      return {
        title: title || "GFG Problem",
        url: location.href.split("?")[0],
        code: best
      };
    }
  });

  return results?.[0]?.result || null;
}

async function saveSolution() {
  try {
    setStatus("Reading GFG page...");

    const settings = await getSettings();
    if (!settings.githubToken || !settings.repo) {
      setStatus("GitHub settings are missing. Open Extension Options and save them once.");
      return;
    }

    const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
    if (!tab?.id || !tab.url?.includes("geeksforgeeks.org")) {
      setStatus("Open a GeeksForGeeks problem page first.");
      return;
    }

    const page = await readGfgPage(tab.id);
    if (!page?.code || page.code.length < 10) {
      setStatus("Could not read the GFG editor. Keep the code visible and click Save Solution again.");
      return;
    }

    const branch = settings.branch || "main";
    const category = detectCategory(page.title, page.url);
    const language = detectLanguage(page.code);
    const ext = extensionFor(language);
    const safeTitle = page.title.replace(/[^a-zA-Z0-9 _-]/g, "").trim() || "solution";
    const folder = `${category}/${safeTitle}`;

    setStatus(`Detected: ${category}\nLanguage: ${language}\nUploading...`);
    await putFile(settings.repo, `${folder}/Solution.${ext}`, page.code + "\n", `feat: add GFG solution - ${page.title}`, branch, settings.githubToken);
    await putFile(settings.repo, `${folder}/README.md`, readme(page.title, page.url, language, category), `docs: add README for GFG - ${page.title}`, branch, settings.githubToken);
    setStatus(`Saved!\n${folder}/Solution.${ext}\n${folder}/README.md`);
  } catch (error) {
    console.error("GFG Sync error:", error);
    setStatus(`Error: ${error.message}`);
  }
}

document.getElementById("save").addEventListener("click", saveSolution);
