const status = document.getElementById("status");
const setStatus = (text) => { status.textContent = text; };

async function getSettings() {
  return chrome.storage.local.get(["githubToken", "repo", "branch"]);
}

function detectCategory(title, url) {
  const text = `${title} ${url}`.toLowerCase();
  const rules = [
    ["Arrays", ["array", "subarray", "subsequence", "two sum", "kadane", "rotate array"]],
    ["Strings", ["string", "palindrome", "anagram", "substring"]],
    ["LinkedList", ["linked list", "doubly linked", "circular linked"]],
    ["Stack", ["stack", "parenthesis", "balanced brackets"]],
    ["Queue", ["queue", "deque"]],
    ["Trees", ["binary tree", "bst", "binary search tree", "tree traversal"]],
    ["Graphs", ["graph", "bfs", "dfs", "dijkstra", "topological"]],
    ["Dynamic Programming", ["dynamic programming", "knapsack", "memoization"]],
    ["Searching", ["binary search", "search in", "searching"]],
    ["Sorting", ["sort", "sorting", "merge sort", "quick sort"]],
    ["Mathematics", ["prime", "factorial", "gcd", "lcm", "fibonacci", "number", "divisor", "power"]],
    ["Bit Manipulation", ["bit manipulation", "bitwise", "xor", "set bit"]],
    ["Greedy", ["greedy"]],
    ["Heap", ["heap", "priority queue", "kth largest", "kth smallest"]]
  ];
  for (const [category, words] of rules) if (words.some(w => text.includes(w))) return category;
  return "Miscellaneous";
}

function detectLanguage(code, editorLanguage) {
  if (editorLanguage && editorLanguage !== "text") {
    const l = editorLanguage.toLowerCase();
    if (l.includes("java")) return "Java";
    if (l.includes("python")) return "Python";
    if (l.includes("c++") || l.includes("cpp") || l.includes("c_cpp")) return "C++";
    if (l.includes("javascript")) return "JavaScript";
  }
  if (/\bclass\s+Solution\b|System\.out\.println|import\s+java\.|\bpublic\s+static\s+/.test(code)) return "Java";
  if (/\bdef\s+\w+\s*\(|import\s+(numpy|pandas)|\bprint\s*\(/.test(code)) return "Python";
  if (/#include\s*</.test(code) || /std::cout|using\s+namespace\s+std/.test(code)) return "C++";
  if (/console\.log\s*\(|function\s+\w+\s*\(/.test(code)) return "JavaScript";
  return "Java";
}

function extensionFor(language) {
  return { Java: "java", Python: "py", "C++": "cpp", JavaScript: "js" }[language] || "txt";
}

function readme(title, url, language, category) {
  return `# ${title}\n\n- **Platform:** GeeksForGeeks\n- **Category:** ${category}\n- **Language:** ${language}\n- **Problem:** ${url}\n\n## Approach\n\nSolution synced automatically from the GFG editor.\n\n## Notes\n\nThis file was generated by GFG → GitHub Sync.\n`;
}

function b64(text) {
  return btoa(unescape(encodeURIComponent(text)));
}

async function putFile(repo, path, content, message, branch, token) {
  const encodedPath = path.split("/").map(encodeURIComponent).join("/");
  const base = `https://api.github.com/repos/${repo}/contents/${encodedPath}`;
  let sha;
  const existing = await fetch(`${base}?ref=${encodeURIComponent(branch)}`, {
    headers: { Authorization: `Bearer ${token}`, Accept: "application/vnd.github+json" }
  });
  if (existing.ok) sha = (await existing.json()).sha;
  const body = { message, content: b64(content), branch };
  if (sha) body.sha = sha;
  const response = await fetch(base, {
    method: "PUT",
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "Content-Type": "application/json"
    },
    body: JSON.stringify(body)
  });
  const data = await response.json();
  if (!response.ok) throw new Error(data.message || `GitHub HTTP ${response.status}`);
  return data;
}

async function readGfgPage(tabId) {
  const results = await chrome.scripting.executeScript({
    target: { tabId },
    func: () => {
      const clean = (v) => (v || "").replace(/\u00a0/g, " ").replace(/\r/g, "").trim();
      const editors = [...document.querySelectorAll(".ace_editor")];
      let best = "";

      for (const editor of editors) {
        // This is the exact GFG/Ace path that exposes the source in the editor DOM.
        const textLayer = editor.querySelector(".ace_text-layer");
        const layerText = clean(textLayer?.innerText || textLayer?.textContent);
        if (layerText.length > best.length) best = layerText;

        // Direct editor text fallback.
        const editorText = clean(editor.innerText || editor.textContent);
        if (editorText.length > best.length) best = editorText;
      }

      // Remove Ace line-number prefixes when .ace_editor.innerText is used.
      if (best) {
        const lines = best.split("\n");
        if (lines.length > 2 && lines.slice(0, Math.min(8, lines.length)).every(x => /^\s*\d+\s*$/.test(x))) {
          let i = 0;
          while (i < lines.length && /^\s*\d+\s*$/.test(lines[i])) i++;
          best = lines.slice(i).join("\n").trim();
        }
      }

      // Other editor fallbacks.
      if (best.length < 10) {
        for (const el of document.querySelectorAll("textarea, [contenteditable='true'], pre code")) {
          const value = clean(el.value || el.innerText || el.textContent);
          if (value.length > best.length) best = value;
        }
      }

      const title = document.querySelector("h1")?.innerText?.trim() || document.title.replace(/\s*[-|].*$/, "").trim() || "GFG Problem";
      return {
        title,
        url: location.href.split("?")[0],
        code: best,
        editorLanguage: "Java"
      };
    }
  });
  return results?.[0]?.result || null;
}

async function saveSolution() {
  try {
    setStatus("Reading GFG page...");
    const settings = await getSettings();
    if (!settings.githubToken || !settings.repo) {
      setStatus("GitHub settings are missing. Open Extension Options and save them once.");
      return;
    }

    const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
    if (!tab?.id || !tab.url?.includes("geeksforgeeks.org")) {
      setStatus("Open a GeeksForGeeks problem page first.");
      return;
    }

    const page = await readGfgPage(tab.id);
    if (!page?.code || page.code.length < 10) {
      setStatus("Could not read the GFG editor. Keep the code visible and click Save Solution again.");
      return;
    }

    const branch = settings.branch || "main";
    const category = detectCategory(page.title, page.url);
    const language = detectLanguage(page.code, page.editorLanguage);
    const ext = extensionFor(language);
    const safeTitle = page.title.replace(/[^a-zA-Z0-9 _-]/g, "").trim() || "solution";
    const folder = `${category}/${safeTitle}`;

    setStatus(`Detected: ${category}\nLanguage: ${language}\nUploading...`);
    await putFile(settings.repo, `${folder}/Solution.${ext}`, page.code + "\n", `feat: add GFG solution - ${page.title}`, branch, settings.githubToken);
    await putFile(settings.repo, `${folder}/README.md`, readme(page.title, page.url, language, category), `docs: add README for GFG - ${page.title}`, branch, settings.githubToken);
    setStatus(`Saved!\n${folder}/Solution.${ext}\n${folder}/README.md`);
  } catch (error) {
    console.error("GFG Sync error:", error);
    setStatus(`Error: ${error.message}`);
  }
}

document.getElementById("save").addEventListener("click", saveSolution);
